title <- "Progetto Business Intelligence Lissoni Edoardo"

ui <- fluidPage(
  useShinyjs(),
  titlePanel(title),
    navbarPage( title = NULL,
                tabPanel(title="Descriptive Analytics",
                         sidebarLayout( 
                            sidebarPanel("",
                                         checkboxGroupInput(inputId ="stocksCheckBox",
                                                            label="Select stocks:", 
                                                            choices=c("MONSTER BEVERAGE" = stocks[1],
                                                                      "PEPSI" = stocks[2],
                                                                      "RYANAIR" = stocks[3],
                                                                      "ALLEGIANT CO." = stocks[4],
                                                                      "AMD" = stocks[5],
                                                                      "NVIDIA" = stocks[6])),
                                         
                                         radioButtons(inputId ="indexRadioBtn",
                                                      label="Select Market Index:", 
                                                      choices=c("S&P 500",
                                                                "DOW JONES",
                                                                "NASDAQ"),
                                                      selected = "NASDAQ"),
                                         ), 
                            mainPanel("",
                                      conditionalPanel(condition = "input.stocksCheckBox.length > 0",
                                        tags$h4(tags$b(textOutput(outputId = "simpleCCReturnsOut")),
                                                        style = "text-align: center"),
                                        plotOutput(outputId = "simpleCCReturnsPlot"),
                                        conditionalPanel(condition = "input.stocksCheckBox.length == 1",
                                                         plotOutput(outputId = "betaPlotOut"),
                                                         plotOutput(outputId = "stockIndexPlotOut"),
                                                         plotOutput(outputId = "diagnosticPlotOut"),               
                                        ),
                                        conditionalPanel(condition = "input.stocksCheckBox.length > 1",
                                                         plotOutput(outputId = "correlationPairsPlotOut"),
                                                         tags$h4(tags$b(textOutput(outputId = "correlationTextOut")),
                                                                 style = "text-align: center"),
                                                         tags$div(plotOutput(outputId = "corrDataPlotOut"),
                                                                  style = "display: flex justify-content: flex-start")
                                        ),
                                      ),
                            ),
                          ),
                 ),
                 tabPanel(title="Predictive Analytics",
                          sidebarLayout( 
                            sidebarPanel("",
                                         radioButtons(inputId ="forecastRadioBtn",
                                                      label="Select Stock:", 
                                                      choices=c("MONSTER BEVERAGE" = stocks[1],
                                                                "PEPSI" = stocks[2],
                                                                "RYANAIR" = stocks[3],
                                                                "ALLEGIANT CO." = stocks[4],
                                                                "AMD" = stocks[5],
                                                                "NVIDIA" = stocks[6]),
                                                      ),
                                         numericInput(inputId = "forecastNValue",
                                                      label = "Select the number of training set months:",
                                                      value = 80,
                                                      max = 120,
                                                      min = 0,
                                                      ),
                                         numericInput(inputId = "forecastMValue",
                                                      label = "Select the number of test set months:",
                                                      value = 30,
                                                      max = 120,
                                                      min = 0,
                                                      ),
                                         actionButton(inputId = "forecastBtn",
                                                      label = "Predict",
                                                      ),
                                         helpText("Select the number of months of testing and training in 
                                                  such a way that their sum is not strictly greater than 120"),
                            ),
                            mainPanel("",
                              plotOutput(outputId = "forecastPlot"),
                              tags$h3(tags$b(textOutput(outputId = "forecastErrorText"))),
                              ),
                          ),
                 ),
                 tabPanel(title="Portfolio Management",
                          sidebarLayout( 
                            sidebarPanel("",
                                         checkboxGroupInput(inputId ="portfolioStocksCheckBox",
                                                            label="Select stocks:", 
                                                            choices=c("MONSTER BEVERAGE" = stocks[1],
                                                                      "PEPSI" = stocks[2],
                                                                      "RYANAIR" = stocks[3],
                                                                      "ALLEGIANT TRAVEL CO." = stocks[4],
                                                                      "AMD" = stocks[5],
                                                                      "NVIDIA" = stocks[6])),
                                         numericInput(inputId = "portfolioBudget",
                                                      label = "Select the budget:",
                                                      value = 1000,
                                                      min = 10,
                                         ),
                            ),
                            mainPanel("",
                                      conditionalPanel(condition = "input.portfolioStocksCheckBox.length > 1",
                                                       plotOutput(outputId = "showPortfolio"),
                                                       tags$h6(verbatimTextOutput(outputId = "portfolioWeights")))),
                          ),
                 ),
                 id = "subTitle", selected = FALSE,
                 position = "static-top",
                 header = NULL,
                 footer = NULL, inverse = FALSE,
                 collapsible = FALSE, fluid = FALSE,
                 theme = NULL, windowTitle = title
               ),
)

